#!/bin/bash

set -e

DEFAULT_FILENAME="docker-raft"
DEFAULT_TARGET_DIR="~/.docker/cli-plugins/"
SOURCE_URL="https://raw.githubusercontent.com/snth/docker-stack/main/docker-raft"

expand_tilde() {
    tilde_less="${1#\~/}"
    [ "$1" != "$tilde_less" ] && tilde_less="$HOME/$tilde_less"
    printf '%s' "$tilde_less"
}

read -p "Installation directory? [$DEFAULT_TARGET_DIR] " TARGET_DIR

TARGET_DIR=$(expand_tilde "${TARGET_DIR:-$DEFAULT_TARGET_DIR}")
if [ ! -d "$TARGET_DIR" ]; then
    read -p "Create directory \"$TARGET_DIR\"? [y/N] "
    if [[ $REPLY != [yY]* ]]; then
        echo "Aborting. Good bye!"
        exit 0
    fi
    mkdir -p "$TARGET_DIR"
fi

read -p "Filename? [$DEFAULT_FILENAME] " FILENAME

TARGET="${TARGET_DIR%/}/$(basename ${FILENAME:-$DEFAULT_FILENAME})"
cat <<EOF
Installing 
    from: $SOURCE_URL 
    to:   $TARGET

EOF
read -p "Continue? [y/N] "
if [[ $REPLY != [yY]* ]]; then
    echo "Aborting. Good bye!"
    exit 0
fi
curl --silent --show-error "$SOURCE_URL" -o "$TARGET"
chmod +x $TARGET
echo "File written to: $TARGET"
echo "Installation complete!"
